# # SCCN
# Fixed split
python train.py dataset=ZINC model=simplicial/sccn model.optimizer.lr=0.01 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=64 model.backbone.n_layers=2,4 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean callbacks.early_stopping.min_delta=0.005 dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun  
python train.py dataset=ZINC model=simplicial/sccn model.optimizer.lr=0.01 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=2,4 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean callbacks.early_stopping.min_delta=0.005 dataset.transforms.graph2simplicial_lifting.signed=True,False dataset.transforms.graph2simplicial_lifting.feature_lifting=concatenation --multirun  
python train.py dataset=ZINC model=simplicial/sccn model.optimizer.lr=0.01 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=2,4 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean callbacks.early_stopping.min_delta=0.005 dataset.transforms.graph2simplicial_lifting.signed=True,False dataset.transforms.graph2simplicial_lifting.feature_lifting=set model.feature_encoder._target_=topobenchmarkx.models.encoders.default_encoders.SetFeatureEncoder --multirun  
# Batch size =1
python train.py dataset=cocitation_cora model=simplicial/sccn model.optimizer.lr=0.01 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=32,64 model.backbone.n_layers=1,2 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
python train.py dataset=cocitation_citeseer model=simplicial/sccn model.optimizer.lr=0.01 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=32,64 model.backbone.n_layers=1,2 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
python train.py dataset=cocitation_pubmed model=simplicial/sccn model.optimizer.lr=0.01 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=32,64 model.backbone.n_layers=1,2 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
# Vary batch size
python train.py dataset=PROTEINS_TU model=simplicial/sccn model.optimizer.lr=0.001 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
python train.py dataset=PROTEINS_TU model=simplicial/sccn model.optimizer.lr=0.001 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False dataset.transforms.graph2simplicial_lifting.feature_lifting=concatenation --multirun
python train.py dataset=PROTEINS_TU model=simplicial/sccn model.optimizer.lr=0.001 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False dataset.transforms.graph2simplicial_lifting.feature_lifting=set model.feature_encoder._target_=topobenchmarkx.models.encoders.default_encoders.SetFeatureEncoder --multirun

python train.py dataset=NCI1 model=simplicial/sccn model.optimizer.lr=0.001 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
python train.py dataset=NCI1 model=simplicial/sccn model.optimizer.lr=0.001 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False dataset.transforms.graph2simplicial_lifting.feature_lifting=concatenation --multirun
python train.py dataset=NCI1 model=simplicial/sccn model.optimizer.lr=0.001 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False dataset.transforms.graph2simplicial_lifting.feature_lifting=set model.feature_encoder._target_=topobenchmarkx.models.encoders.default_encoders.SetFeatureEncoder --multirun

python train.py dataset=MUTAG model=simplicial/sccn model.optimizer.lr=0.001 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
python train.py dataset=MUTAG model=simplicial/sccn model.optimizer.lr=0.001 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False dataset.transforms.graph2simplicial_lifting.feature_lifting=concatenation --multirun
python train.py dataset=MUTAG model=simplicial/sccn model.optimizer.lr=0.001 model.backbone.max_rank=1,2 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False dataset.transforms.graph2simplicial_lifting.feature_lifting=set model.feature_encoder._target_=topobenchmarkx.models.encoders.default_encoders.SetFeatureEncoder --multirun

# python train.py dataset=IMDB-BINARY model=simplicial/sccn model.optimizer.lr=0.01,0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean --multirun
# python train.py dataset=IMDB-MULTI model=simplicial/sccn model.optimizer.lr=0.01,0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean --multirun

# SCCNN
# Fixed split
python train.py dataset=ZINC model=simplicial/sccnn model.optimizer.lr=0.01 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=2,4 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean callbacks.early_stopping.min_delta=0.005 dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
# Batch size =1
python train.py dataset=cocitation_cora model=simplicial/sccnn model.optimizer.lr=0.01 model.feature_encoder.out_channels=32,64 model.backbone.n_layers=1,2 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
python train.py dataset=cocitation_citeseer model=simplicial/sccnn model.optimizer.lr=0.01 model.feature_encoder.out_channels=32,64 model.backbone.n_layers=1,2 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
python train.py dataset=cocitation_pubmed model=simplicial/sccnn model.optimizer.lr=0.01 model.feature_encoder.out_channels=32,64 model.backbone.n_layers=1,2 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
# Vary batch size
python train.py dataset=PROTEINS_TU model=simplicial/sccnn model.optimizer.lr=0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
python train.py dataset=NCI1 model=simplicial/sccnn model.optimizer.lr=0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
python train.py dataset=MUTAG model=simplicial/sccnn model.optimizer.lr=0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
# python train.py dataset=IMDB-BINARY model=simplicial/sccn model.optimizer.lr=0.01,0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean --multirun
# python train.py dataset=IMDB-MULTI model=simplicial/sccn model.optimizer.lr=0.01,0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean --multirun


# SCCNN_custom
# Fixed split
python train.py dataset=ZINC model=simplicial/sccnn_custom model.optimizer.lr=0.01 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=2,4 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean callbacks.early_stopping.min_delta=0.005 dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
# Batch size =1
python train.py dataset=cocitation_cora model=simplicial/sccnn_custom model.optimizer.lr=0.01 model.feature_encoder.out_channels=32,64 model.backbone.n_layers=1,2 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
python train.py dataset=cocitation_citeseer model=simplicial/sccnn_custom model.optimizer.lr=0.01 model.feature_encoder.out_channels=32,64 model.backbone.n_layers=1,2 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
python train.py dataset=cocitation_pubmed model=simplicial/sccnn_custom model.optimizer.lr=0.01 model.feature_encoder.out_channels=32,64 model.backbone.n_layers=1,2 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
# Vary batch size
python train.py dataset=PROTEINS_TU model=simplicial/sccnn_custom model.optimizer.lr=0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
python train.py dataset=NCI1 model=simplicial/sccnn_custom model.optimizer.lr=0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
python train.py dataset=MUTAG model=simplicial/sccnn_custom model.optimizer.lr=0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.transforms.graph2simplicial_lifting.complex_dim=3 model.backbone_wrapper.wrapper_readout=original,signal_prop_down model.readout.pooling_type=sum,mean dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun



# SCN
# Fixed split
python train.py dataset=ZINC model=simplicial/scn model.optimizer.lr=0.01,0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2,4 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.dataset.transforms.graph2simplicial_lifting.complex_dim=3 callbacks.early_stopping.min_delta=0.005 dataset.transforms.graph2simplicial_lifting.signed=True,False --multirun
# Batch size =1
python train.py dataset=cocitation_cora model=simplicial/scn model.optimizer.lr=0.01,0.001 model.feature_encoder.out_channels=32,64 model.backbone.n_layers=1,2 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.dataset.transforms.graph2simplicial_lifting.complex_dim=3 dataset.transforms.graph2simplicial_lifting.signed=True --multirun
python train.py dataset=cocitation_citeseer model=simplicial/scn model.optimizer.lr=0.01,0.001 model.feature_encoder.out_channels=32,64 model.backbone.n_layers=1,2 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.dataset.transforms.graph2simplicial_lifting.complex_dim=3 dataset.transforms.graph2simplicial_lifting.signed=True --multirun
python train.py dataset=cocitation_pubmed model=simplicial/scn model.optimizer.lr=0.01,0.001 model.feature_encoder.out_channels=32,64 model.backbone.n_layers=1,2 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.dataset.transforms.graph2simplicial_lifting.complex_dim=3 dataset.transforms.graph2simplicial_lifting.signed=True --multirun
# Vary batch size
python train.py dataset=PROTEINS_TU model=simplicial/scn model.optimizer.lr=0.01,0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.dataset.transforms.graph2simplicial_lifting.complex_dim=3 dataset.transforms.graph2simplicial_lifting.signed=True --multirun
python train.py dataset=NCI1 model=simplicial/scn model.optimizer.lr=0.01,0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.dataset.transforms.graph2simplicial_lifting.complex_dim=3 dataset.transforms.graph2simplicial_lifting.signed=True --multirun
python train.py dataset=MUTAG model=simplicial/scn model.optimizer.lr=0.01,0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.dataset.transforms.graph2simplicial_lifting.complex_dim=3 dataset.transforms.graph2simplicial_lifting.signed=True --multirun
# python train.py dataset=IMDB-BINARY model=simplicial/sccn model.optimizer.lr=0.01,0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.dataset.transforms.graph2simplicial_lifting.complex_dim=3 --multirun
# python train.py dataset=IMDB-MULTI model=simplicial/sccn model.optimizer.lr=0.01,0.001 model.feature_encoder.out_channels=16,64 model.backbone.n_layers=1,2 dataset.parameters.batch_size=128 dataset.parameters.data_seed=0,3,5 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 trainer=default logger.wandb.project=topobenchmark_0503 dataset.dataset.transforms.graph2simplicial_lifting.complex_dim=3 --multirun
