#!/bin/bash

# Define log files
LOG_FILE="scripts/script_output.log"
ERROR_LOG_FILE="scripts/script_error.log"
FAILED_LOG_FILE="scripts/failed_runs.log"

# Clear previous log files
> $LOG_FILE
> $ERROR_LOG_FILE
> $FAILED_LOG_FILE

# Function to run a command and check for failure
run_command() {
    local cmd="$1"
    
    # Run the command and capture the output and error
    { eval "$cmd" 2>&1 | tee -a "$LOG_FILE"; } 2>> "$ERROR_LOG_FILE"
    
    # Check if the command failed
    if [ ${PIPESTATUS[0]} -ne 0 ]; then
        echo "Command failed: $cmd" >> "$FAILED_LOG_FILE"
        echo "Check $ERROR_LOG_FILE for details." >> "$FAILED_LOG_FILE"
    fi
}

# List of commands to execute
commands=(
# SCCNN
'python -m topobenchmarkx model=simplicial/sccnn_custom dataset=graph/MUTAG optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=1 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=32 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom dataset=graph/NCI1 optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=64 model.backbone.n_layers=2 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom dataset=graph/NCI109 optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=32 model.backbone.n_layers=2 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom dataset=graph/PROTEINS optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=1 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom dataset=graph/US-county-demos optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=128 model.backbone.n_layers=1 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.loader.parameters.task_variable=Election dataset.loader.parameters.year=2012 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom dataset=graph/ZINC optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.n_layers=4 model.readout.readout_name=PropagateSignalDown transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 callbacks.early_stopping.min_delta=0.005 transforms.one_hot_node_degree_features.degrees_fields=x seed=42,3,5,23,150 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom dataset=graph/cocitation_citeseer optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.n_layers=2 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom dataset=graph/cocitation_cora optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=1 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom dataset=graph/cocitation_pubmed optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=128 model.backbone.n_layers=1 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom dataset=graph/minesweeper optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=32 model.backbone.n_layers=1 model.readout.readout_name=PropagateSignalDown transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom dataset=graph/roman_empire optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.n_layers=2 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
# SCN
'python -m topobenchmarkx model=simplicial/scn dataset=graph/MUTAG optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=3 model.readout.readout_name=PropagateSignalDown transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=64 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn dataset=graph/NCI1 optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=64 model.backbone.n_layers=4 model.readout.readout_name=PropagateSignalDown transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn dataset=graph/NCI109 optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=4 model.readout.readout_name=PropagateSignalDown transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn dataset=graph/PROTEINS optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=2 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn dataset=graph/US-county-demos optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=4 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.loader.parameters.task_variable=Election dataset.loader.parameters.year=2012 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn dataset=graph/ZINC optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=4 model.readout.readout_name=PropagateSignalDown transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=256 callbacks.early_stopping.min_delta=0.005 transforms.one_hot_node_degree_features.degrees_fields=x seed=42,3,5,23,150 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn dataset=graph/cocitation_citeseer optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.n_layers=1 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn dataset=graph/cocitation_cora optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=1 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn dataset=graph/cocitation_pubmed optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.n_layers=2 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn dataset=graph/minesweeper optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.n_layers=3 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn dataset=graph/roman_empire optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=128 model.backbone.n_layers=3 model.readout.readout_name=PropagateSignalDown transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'

# SCCNN
'python -m topobenchmarkx model=simplicial/sccnn_custom transforms=curvature_simplicial tags=["curvature"] dataset=graph/MUTAG optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=1 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=32 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom transforms=curvature_simplicial tags=["curvature"] dataset=graph/NCI1 optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=64 model.backbone.n_layers=2 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom transforms=curvature_simplicial tags=["curvature"] dataset=graph/NCI109 optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=32 model.backbone.n_layers=2 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom transforms=curvature_simplicial tags=["curvature"] dataset=graph/PROTEINS optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=1 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom transforms=curvature_simplicial tags=["curvature"] dataset=graph/US-county-demos optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=128 model.backbone.n_layers=1 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.loader.parameters.task_variable=Election dataset.loader.parameters.year=2012 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
#'python -m topobenchmarkx model=simplicial/sccnn_custom transforms=curvature_simplicial tags=["curvature"] dataset=graph/ZINC optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.n_layers=4 model.readout.readout_name=PropagateSignalDown transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 callbacks.early_stopping.min_delta=0.005 transforms.one_hot_node_degree_features.degrees_fields=x seed=42,3,5,23,150 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom transforms=curvature_simplicial tags=["curvature"] dataset=graph/cocitation_citeseer optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.n_layers=2 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom transforms=curvature_simplicial tags=["curvature"] dataset=graph/cocitation_cora optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=1 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom transforms=curvature_simplicial tags=["curvature"] dataset=graph/cocitation_pubmed optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=128 model.backbone.n_layers=1 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom transforms=curvature_simplicial tags=["curvature"] dataset=graph/minesweeper optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=32 model.backbone.n_layers=1 model.readout.readout_name=PropagateSignalDown transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/sccnn_custom transforms=curvature_simplicial tags=["curvature"] dataset=graph/roman_empire optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.n_layers=2 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
# SCN
'python -m topobenchmarkx model=simplicial/scn transforms=curvature_simplicial tags=["curvature"] dataset=graph/MUTAG optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=3 model.readout.readout_name=PropagateSignalDown transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=64 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn transforms=curvature_simplicial tags=["curvature"] dataset=graph/NCI1 optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=64 model.backbone.n_layers=4 model.readout.readout_name=PropagateSignalDown transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn transforms=curvature_simplicial tags=["curvature"] dataset=graph/NCI109 optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=4 model.readout.readout_name=PropagateSignalDown transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn transforms=curvature_simplicial tags=["curvature"] dataset=graph/PROTEINS optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=2 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn transforms=curvature_simplicial tags=["curvature"] dataset=graph/US-county-demos optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=4 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.loader.parameters.task_variable=Election dataset.loader.parameters.year=2012 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
#'python -m topobenchmarkx model=simplicial/scn transforms=curvature_simplicial tags=["curvature"] dataset=graph/ZINC optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=4 model.readout.readout_name=PropagateSignalDown transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=256 callbacks.early_stopping.min_delta=0.005 transforms.one_hot_node_degree_features.degrees_fields=x seed=42,3,5,23,150 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn transforms=curvature_simplicial tags=["curvature"] dataset=graph/cocitation_citeseer optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.n_layers=1 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn transforms=curvature_simplicial tags=["curvature"] dataset=graph/cocitation_cora optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.n_layers=1 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn transforms=curvature_simplicial tags=["curvature"] dataset=graph/cocitation_pubmed optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.n_layers=2 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn transforms=curvature_simplicial tags=["curvature"] dataset=graph/minesweeper optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.n_layers=3 model.readout.readout_name=NoReadOut transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=simplicial/scn transforms=curvature_simplicial tags=["curvature"] dataset=graph/roman_empire optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=128 model.backbone.n_layers=3 model.readout.readout_name=PropagateSignalDown transforms.graph2simplicial_lifting.signed=True model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'

# GCN
'python -m topobenchmarkx model=graph/gcn dataset=graph/MUTAG optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.num_layers=3 model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=32 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn dataset=graph/NCI1 optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.num_layers=4 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn dataset=graph/NCI109 optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.num_layers=4 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn dataset=graph/PROTEINS optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.num_layers=2 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=256 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn dataset=graph/US-county-demos optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.num_layers=4 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=1 dataset.loader.parameters.task_variable=Election dataset.loader.parameters.year=2012 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn dataset=graph/cocitation_citeseer optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.num_layers=2 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn dataset=graph/cocitation_cora optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.num_layers=2 model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn dataset=graph/cocitation_pubmed optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.num_layers=2 model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn dataset=graph/minesweeper optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.num_layers=1 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn dataset=graph/roman_empire optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.num_layers=3 model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'


# GCN rewire
'python -m topobenchmarkx model=graph/gcn transforms=curvature tags=["curvature"] dataset=graph/MUTAG optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.num_layers=3 model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=32 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn transforms=curvature tags=["curvature"] dataset=graph/NCI1 optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=32 model.backbone.num_layers=4 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn transforms=curvature tags=["curvature"] dataset=graph/NCI109 optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.num_layers=4 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn transforms=curvature tags=["curvature"] dataset=graph/PROTEINS optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.num_layers=2 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=256 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 callbacks.early_stopping.patience=10 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn transforms=curvature tags=["curvature"] dataset=graph/US-county-demos optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.num_layers=4 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=1 dataset.loader.parameters.task_variable=Election dataset.loader.parameters.year=2012 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn transforms=curvature tags=["curvature"] dataset=graph/cocitation_citeseer optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.num_layers=2 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn transforms=curvature tags=["curvature"] dataset=graph/cocitation_cora optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.num_layers=2 model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn transforms=curvature tags=["curvature"] dataset=graph/cocitation_pubmed optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.num_layers=2 model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn transforms=curvature tags=["curvature"] dataset=graph/minesweeper optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.num_layers=1 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
'python -m topobenchmarkx model=graph/gcn transforms=curvature tags=["curvature"] dataset=graph/roman_empire optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.num_layers=3 model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=1 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=1 callbacks.early_stopping.patience=50 logger.wandb.project=TopoBenchmarkX_curvature --multirun'
)

# Iterate over the commands and run them
for cmd in "${commands[@]}"; do
    echo "Running: $cmd"
    run_command "$cmd"
done


