# Dataset loader config
loader:
  _target_: topobenchmark.data.loaders.USCountyDemosDatasetLoader
  parameters: 
    data_domain: graph
    data_type: cornel
    data_name: US-county-demos
    year: 2012
    task_variable: 'Election' # options: ['Election', 'MedianIncome', 'MigraRate', 'BirthRate', 'DeathRate', 'BachelorRate', 'UnemploymentRate']
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 6
  num_classes: 1
  task: regression
  loss_type: mse
  monitor_metric: mae
  task_level: node

#splits
split_params:
  learning_setting: transductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation
  train_prop: 0.5 # for "random" strategy splitting
  standardize: True

# Dataloader parameters
dataloader_params:
  batch_size: -1 # Fixed
  num_workers: 0
  pin_memory: False
